-- Security observability and access hardening after the 2026-07-27 incident.
-- Idempotent migration; database.sql remains the canonical bootstrap schema.

-- ---------------------------------------------------------------------------
-- 1. Central security events and distributed rate limits
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.security_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::TEXT, NOW()),
  event_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'low',
  source TEXT NOT NULL DEFAULT 'database',
  actor_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  target_type TEXT,
  target_id TEXT,
  request_id TEXT,
  ip_hash TEXT,
  user_agent TEXT,
  path TEXT,
  fingerprint TEXT,
  details JSONB NOT NULL DEFAULT '{}'::JSONB,
  CONSTRAINT security_events_type_check
    CHECK (event_type ~ '^[a-z0-9][a-z0-9._-]{1,79}$'),
  CONSTRAINT security_events_severity_check
    CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  CONSTRAINT security_events_source_check
    CHECK (source ~ '^[a-z0-9][a-z0-9._-]{1,39}$'),
  CONSTRAINT security_events_lengths_check
    CHECK (
      char_length(COALESCE(target_type, '')) <= 80
      AND char_length(COALESCE(target_id, '')) <= 200
      AND char_length(COALESCE(request_id, '')) <= 160
      AND char_length(COALESCE(ip_hash, '')) <= 128
      AND char_length(COALESCE(user_agent, '')) <= 512
      AND char_length(COALESCE(path, '')) <= 1024
      AND char_length(COALESCE(fingerprint, '')) <= 128
      AND octet_length(details::TEXT) <= 8192
    ),
  CONSTRAINT security_events_no_top_level_secrets_check
    CHECK (
      NOT (
        details ?| ARRAY[
          'authorization', 'cookie', 'password', 'access_token', 'refresh_token',
          'service_role', 'secret', 'api_key', 'apikey'
        ]
      )
    )
);

CREATE INDEX IF NOT EXISTS idx_security_events_occurred
  ON public.security_events(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_severity_occurred
  ON public.security_events(severity, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_type_occurred
  ON public.security_events(event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_actor_occurred
  ON public.security_events(actor_user_id, occurred_at DESC)
  WHERE actor_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_security_events_fingerprint_occurred
  ON public.security_events(fingerprint, occurred_at DESC)
  WHERE fingerprint IS NOT NULL;

ALTER TABLE public.security_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.security_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.security_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.security_events_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.security_rate_limits (
  scope TEXT NOT NULL,
  key_hash TEXT NOT NULL,
  window_started_at TIMESTAMPTZ NOT NULL,
  request_count INTEGER NOT NULL DEFAULT 1 CHECK (request_count >= 1),
  expires_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (scope, key_hash, window_started_at),
  CONSTRAINT security_rate_limits_scope_check
    CHECK (scope ~ '^[a-z0-9][a-z0-9._-]{1,79}$'),
  CONSTRAINT security_rate_limits_key_check
    CHECK (char_length(key_hash) BETWEEN 16 AND 128)
);

CREATE INDEX IF NOT EXISTS idx_security_rate_limits_expires
  ON public.security_rate_limits(expires_at);

ALTER TABLE public.security_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.security_rate_limits FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.security_rate_limits TO service_role;

CREATE OR REPLACE FUNCTION public.security_consume_rate_limit(
  p_scope TEXT,
  p_key_hash TEXT,
  p_limit INTEGER,
  p_window_seconds INTEGER
)
RETURNS TABLE(allowed BOOLEAN, remaining INTEGER, reset_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_now TIMESTAMPTZ := TIMEZONE('utc'::TEXT, NOW());
  v_scope TEXT := lower(trim(COALESCE(p_scope, '')));
  v_key TEXT := lower(trim(COALESCE(p_key_hash, '')));
  v_limit INTEGER := LEAST(10000, GREATEST(1, COALESCE(p_limit, 1)));
  v_window INTEGER := LEAST(86400, GREATEST(10, COALESCE(p_window_seconds, 60)));
  v_start TIMESTAMPTZ;
  v_count INTEGER;
BEGIN
  IF v_scope !~ '^[a-z0-9][a-z0-9._-]{1,79}$'
     OR char_length(v_key) NOT BETWEEN 16 AND 128 THEN
    RAISE EXCEPTION 'invalid_rate_limit_key' USING ERRCODE = '22023';
  END IF;

  v_start := to_timestamp(
    floor(extract(epoch FROM v_now) / v_window) * v_window
  );

  DELETE FROM public.security_rate_limits
  WHERE scope = v_scope
    AND key_hash = v_key
    AND expires_at < v_now;

  INSERT INTO public.security_rate_limits(
    scope, key_hash, window_started_at, request_count, expires_at
  )
  VALUES (
    v_scope, v_key, v_start, 1, v_start + make_interval(secs => v_window * 2)
  )
  ON CONFLICT (scope, key_hash, window_started_at) DO UPDATE
    SET request_count = public.security_rate_limits.request_count + 1,
        expires_at = EXCLUDED.expires_at
  RETURNING request_count INTO v_count;

  RETURN QUERY
  SELECT
    v_count <= v_limit,
    GREATEST(0, v_limit - v_count),
    v_start + make_interval(secs => v_window);
END;
$$;

REVOKE ALL ON FUNCTION public.security_consume_rate_limit(TEXT, TEXT, INTEGER, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.security_consume_rate_limit(TEXT, TEXT, INTEGER, INTEGER)
  TO service_role;

CREATE OR REPLACE FUNCTION public.security_event_summary(
  p_since TIMESTAMPTZ DEFAULT (TIMEZONE('utc'::TEXT, NOW()) - INTERVAL '24 hours')
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_since TIMESTAMPTZ := GREATEST(
    COALESCE(p_since, TIMEZONE('utc'::TEXT, NOW()) - INTERVAL '24 hours'),
    TIMEZONE('utc'::TEXT, NOW()) - INTERVAL '90 days'
  );
  v_result JSONB;
BEGIN
  IF lower(COALESCE(auth.jwt() ->> 'role', '')) <> 'service_role'
     AND (
       auth.uid() IS NULL
       OR NOT public.is_site_creator_user_id(auth.uid())
     ) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  SELECT jsonb_build_object(
    'since', v_since,
    'total', COUNT(*)::BIGINT,
    'critical', COUNT(*) FILTER (WHERE severity = 'critical')::BIGINT,
    'high', COUNT(*) FILTER (WHERE severity = 'high')::BIGINT,
    'medium', COUNT(*) FILTER (WHERE severity = 'medium')::BIGINT,
    'by_type', COALESCE((
      SELECT jsonb_agg(to_jsonb(t) ORDER BY t.count DESC, t.event_type)
      FROM (
        SELECT event_type, COUNT(*)::BIGINT AS count, MAX(occurred_at) AS last_seen_at
        FROM public.security_events
        WHERE occurred_at >= v_since
        GROUP BY event_type
        ORDER BY count DESC
        LIMIT 50
      ) t
    ), '[]'::JSONB)
  )
  INTO v_result
  FROM public.security_events
  WHERE occurred_at >= v_since;

  RETURN COALESCE(v_result, '{}'::JSONB);
END;
$$;

REVOKE ALL ON FUNCTION public.security_event_summary(TIMESTAMPTZ)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.security_event_summary(TIMESTAMPTZ)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.security_delete_expired_events(
  p_retention_days INTEGER DEFAULT 180
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_days INTEGER := LEAST(730, GREATEST(30, COALESCE(p_retention_days, 180)));
  v_count INTEGER;
BEGIN
  DELETE FROM public.security_events
  WHERE occurred_at < TIMEZONE('utc'::TEXT, NOW()) - make_interval(days => v_days);
  GET DIAGNOSTICS v_count = ROW_COUNT;

  DELETE FROM public.security_rate_limits
  WHERE expires_at < TIMEZONE('utc'::TEXT, NOW());

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.security_delete_expired_events(INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.security_delete_expired_events(INTEGER)
  TO service_role;

CREATE OR REPLACE FUNCTION public.security_audit_sensitive_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor UUID := auth.uid();
  v_row JSONB := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  v_old JSONB := CASE WHEN TG_OP = 'UPDATE' THEN to_jsonb(OLD) ELSE '{}'::JSONB END;
  v_target_id TEXT;
  v_type TEXT := lower(TG_TABLE_NAME || '.' || TG_OP);
  v_severity TEXT := 'medium';
  v_changed TEXT[] := ARRAY[]::TEXT[];
  v_request_id TEXT;
BEGIN
  IF TG_TABLE_NAME = 'profiles' AND TG_OP = 'UPDATE' THEN
    IF OLD.is_site_creator IS DISTINCT FROM NEW.is_site_creator THEN v_changed := array_append(v_changed, 'is_site_creator'); END IF;
    IF OLD.role IS DISTINCT FROM NEW.role THEN v_changed := array_append(v_changed, 'role'); END IF;
    IF OLD.is_banned IS DISTINCT FROM NEW.is_banned THEN v_changed := array_append(v_changed, 'is_banned'); END IF;
    IF OLD.ban_reason IS DISTINCT FROM NEW.ban_reason THEN v_changed := array_append(v_changed, 'ban_reason'); END IF;
    IF OLD.banned_at IS DISTINCT FROM NEW.banned_at THEN v_changed := array_append(v_changed, 'banned_at'); END IF;
    IF COALESCE(array_length(v_changed, 1), 0) = 0 THEN
      RETURN NEW;
    END IF;
    v_type := 'profile.security_fields_changed';
    v_severity := 'high';
  ELSIF TG_TABLE_NAME IN ('admins', 'site_team_roles') THEN
    v_type := 'authorization.' || lower(TG_TABLE_NAME) || '.' || lower(TG_OP);
    v_severity := 'critical';
  ELSIF TG_TABLE_NAME IN ('site_maintenance_config', 'minko_ai_public_state') THEN
    v_type := 'site_control.' || lower(TG_TABLE_NAME) || '.' || lower(TG_OP);
    v_severity := 'high';
  ELSIF TG_TABLE_NAME IN ('ai_subscriptions', 'vip_subscriptions') THEN
    v_type := 'subscription.' || lower(TG_TABLE_NAME) || '.' || lower(TG_OP);
    v_severity := 'high';
  ELSIF TG_TABLE_NAME IN ('catalog_site_anime', 'catalog_4k_anime') THEN
    v_type := 'catalog.' || lower(TG_TABLE_NAME) || '.' || lower(TG_OP);
    v_severity := 'high';
  ELSIF TG_TABLE_NAME = 'notifications' THEN
    v_type := 'notification.' || lower(TG_OP);
    v_severity := 'medium';
  END IF;

  v_target_id := COALESCE(
    v_row ->> 'id',
    v_row ->> 'user_id',
    v_row ->> 'target_user_id',
    v_row ->> 'key'
  );

  BEGIN
    v_request_id := left(
      COALESCE(
        current_setting('request.headers', true)::JSONB ->> 'x-request-id',
        current_setting('request.headers', true)::JSONB ->> 'x-client-info',
        ''
      ),
      160
    );
  EXCEPTION WHEN OTHERS THEN
    v_request_id := NULL;
  END;

  INSERT INTO public.security_events(
    event_type,
    severity,
    source,
    actor_user_id,
    target_type,
    target_id,
    request_id,
    fingerprint,
    details
  )
  VALUES (
    left(v_type, 80),
    v_severity,
    'database',
    v_actor,
    left(TG_TABLE_NAME, 80),
    left(COALESCE(v_target_id, ''), 200),
    NULLIF(v_request_id, ''),
    encode(
      digest(
        left(v_type, 80) || ':' || COALESCE(v_actor::TEXT, 'system') || ':' || COALESCE(v_target_id, ''),
        'sha256'
      ),
      'hex'
    ),
    jsonb_build_object(
      'operation', TG_OP,
      'changed_fields', to_jsonb(v_changed),
      'db_role', current_user
    )
  );

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  v_table TEXT;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'profiles',
    'admins',
    'site_team_roles',
    'site_maintenance_config',
    'minko_ai_public_state',
    'ai_subscriptions',
    'vip_subscriptions',
    'catalog_site_anime',
    'catalog_4k_anime',
    'notifications'
  ]
  LOOP
    IF to_regclass('public.' || v_table) IS NOT NULL THEN
      EXECUTE format('DROP TRIGGER IF EXISTS security_audit_change ON public.%I', v_table);
      EXECUTE format(
        'CREATE TRIGGER security_audit_change AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.security_audit_sensitive_change()',
        v_table
      );
    END IF;
  END LOOP;
END
$$;

-- ---------------------------------------------------------------------------
-- 2. Profiles: safe directory view; private base rows
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.profile_directory
WITH (security_barrier = true)
AS
SELECT
  id,
  username,
  avatar,
  gender,
  created_at,
  last_online,
  current_activity,
  is_site_creator
FROM public.profiles;

REVOKE ALL ON TABLE public.profile_directory FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.profile_directory TO anon, authenticated, service_role;

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_avatar_safe_value_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_avatar_safe_value_check
  CHECK (
    avatar IS NULL
    OR (
      char_length(avatar) <= 2048
      AND avatar !~ '[<>[:cntrl:]]'
      AND (
        trim(avatar) ~* '^https://[^[:space:]<>]+$'
        OR (
          trim(avatar) !~* '^[a-z][a-z0-9+.-]*:'
          AND trim(avatar) !~ '^//'
          AND position(E'\\' in avatar) = 0
        )
        OR trim(avatar) ~* '^data:image/(png|jpe?g|gif|webp);base64,[a-z0-9+/=[:space:]]+$'
      )
    )
  );

DROP POLICY IF EXISTS "profiles_select" ON public.profiles;
DROP POLICY IF EXISTS "profiles_select_own_or_creator" ON public.profiles;
CREATE POLICY "profiles_select_own_or_creator" ON public.profiles
  FOR SELECT TO authenticated
  USING (
    auth.uid() = id
    OR public.is_site_creator_user_id(auth.uid())
  );

REVOKE ALL ON TABLE public.profiles FROM anon;
REVOKE SELECT ON TABLE public.profiles FROM authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.profiles TO service_role;

CREATE OR REPLACE FUNCTION public.get_user_email(user_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_caller UUID := auth.uid();
  v_email TEXT;
BEGIN
  IF v_caller IS NULL THEN
    RETURN NULL;
  END IF;
  IF v_caller <> user_id AND NOT public.is_site_creator_user_id(v_caller) THEN
    RETURN NULL;
  END IF;
  SELECT u.email::TEXT INTO v_email FROM auth.users u WHERE u.id = user_id;
  RETURN v_email;
END;
$$;

REVOKE ALL ON FUNCTION public.get_user_email(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_email(UUID) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.protect_profile_security_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor UUID := auth.uid();
  v_jwt_role TEXT := lower(trim(COALESCE(auth.jwt() ->> 'role', '')));
  v_trusted BOOLEAN :=
    public.is_site_creator_user_id(v_actor)
    OR v_jwt_role = 'service_role'
    OR session_user IN ('postgres', 'supabase_admin');
  v_privileged_change BOOLEAN := false;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_privileged_change :=
      COALESCE(NEW.is_site_creator, false)
      OR lower(trim(COALESCE(NEW.role, 'user'))) <> 'user'
      OR COALESCE(NEW.is_banned, false)
      OR NEW.ban_reason IS NOT NULL
      OR NEW.banned_at IS NOT NULL;
  ELSE
    v_privileged_change :=
      OLD.id IS DISTINCT FROM NEW.id
      OR OLD.created_at IS DISTINCT FROM NEW.created_at
      OR OLD.is_site_creator IS DISTINCT FROM NEW.is_site_creator
      OR OLD.role IS DISTINCT FROM NEW.role
      OR OLD.is_banned IS DISTINCT FROM NEW.is_banned
      OR OLD.ban_reason IS DISTINCT FROM NEW.ban_reason
      OR OLD.banned_at IS DISTINCT FROM NEW.banned_at;
  END IF;

  IF v_privileged_change AND NOT v_trusted THEN
    RAISE LOG 'SECURITY_EVENT|profile_privilege_change_blocked|actor=%|target=%|operation=%',
      COALESCE(v_actor::TEXT, 'anonymous'), COALESCE(NEW.id::TEXT, ''), TG_OP;
    RAISE EXCEPTION 'profiles: protected security fields cannot be changed'
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_profile_security_fields_trigger ON public.profiles;
CREATE TRIGGER protect_profile_security_fields_trigger
BEFORE INSERT OR UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.protect_profile_security_fields();

-- Social data remains available to signed-in users, but no longer to the anon key.
DROP POLICY IF EXISTS "favorites_anime_select" ON public.favorites_anime;
CREATE POLICY "favorites_anime_select" ON public.favorites_anime
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "favorites_manga_select" ON public.favorites_manga;
CREATE POLICY "favorites_manga_select" ON public.favorites_manga
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "watch_history_select" ON public.watch_history;
CREATE POLICY "watch_history_select" ON public.watch_history
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "achievements_select_all" ON public.user_achievements;
CREATE POLICY "achievements_select_all" ON public.user_achievements
  FOR SELECT TO authenticated USING (true);

REVOKE SELECT ON TABLE public.favorites_anime, public.favorites_manga,
  public.watch_history, public.user_achievements FROM anon;
GRANT SELECT ON TABLE public.favorites_anime, public.favorites_manga,
  public.watch_history, public.user_achievements TO authenticated;

-- ---------------------------------------------------------------------------
-- 3. Direct and group messages: immutable identities and bounded payloads
-- ---------------------------------------------------------------------------

ALTER TABLE public.direct_messages
  ADD COLUMN IF NOT EXISTS hidden_for UUID[] NOT NULL DEFAULT ARRAY[]::UUID[];
ALTER TABLE public.direct_messages
  DROP CONSTRAINT IF EXISTS direct_messages_safe_payload_check;
ALTER TABLE public.direct_messages
  ADD CONSTRAINT direct_messages_safe_payload_check
  CHECK (
    sender_id <> receiver_id
    AND char_length(trim(message)) BETWEEN 1 AND 12000
    AND COALESCE(cardinality(hidden_for), 0) <= 2
    AND hidden_for <@ ARRAY[sender_id, receiver_id]
  );

CREATE OR REPLACE FUNCTION public.protect_direct_message_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF current_user = 'authenticated' THEN
    IF TG_OP = 'INSERT' THEN
      NEW.sender_id := auth.uid();
      NEW.read := false;
      NEW.created_at := TIMEZONE('utc'::TEXT, NOW());
      NEW.edited_at := NULL;
      NEW.hidden_for := ARRAY[]::UUID[];
    ELSE
      IF OLD.id IS DISTINCT FROM NEW.id
         OR OLD.sender_id IS DISTINCT FROM NEW.sender_id
         OR OLD.receiver_id IS DISTINCT FROM NEW.receiver_id
         OR OLD.message IS DISTINCT FROM NEW.message
         OR OLD.created_at IS DISTINCT FROM NEW.created_at
         OR OLD.edited_at IS DISTINCT FROM NEW.edited_at
         OR OLD.hidden_for IS DISTINCT FROM NEW.hidden_for
         OR NEW.read IS DISTINCT FROM true THEN
        RAISE LOG 'SECURITY_EVENT|direct_message_tamper_blocked|actor=%|message=%',
          COALESCE(auth.uid()::TEXT, 'anonymous'), COALESCE(OLD.id::TEXT, '');
        RAISE EXCEPTION 'direct_messages: only read=true can be changed directly'
          USING ERRCODE = '42501';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_direct_message_fields_trigger ON public.direct_messages;
CREATE TRIGGER protect_direct_message_fields_trigger
BEFORE INSERT OR UPDATE ON public.direct_messages
FOR EACH ROW EXECUTE FUNCTION public.protect_direct_message_fields();

DROP POLICY IF EXISTS "dm_select" ON public.direct_messages;
DROP POLICY IF EXISTS "dm_insert" ON public.direct_messages;
DROP POLICY IF EXISTS "dm_update" ON public.direct_messages;
DROP POLICY IF EXISTS "dm_delete" ON public.direct_messages;
CREATE POLICY "dm_select" ON public.direct_messages
  FOR SELECT TO authenticated
  USING (
    (auth.uid() = sender_id OR auth.uid() = receiver_id)
    AND NOT (auth.uid() = ANY(hidden_for))
  );
CREATE POLICY "dm_insert" ON public.direct_messages
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = sender_id AND sender_id <> receiver_id);
CREATE POLICY "dm_mark_read" ON public.direct_messages
  FOR UPDATE TO authenticated
  USING (auth.uid() = receiver_id)
  WITH CHECK (auth.uid() = receiver_id);

REVOKE ALL ON TABLE public.direct_messages FROM anon;
REVOKE UPDATE, DELETE ON TABLE public.direct_messages FROM authenticated;
GRANT SELECT, INSERT ON TABLE public.direct_messages TO authenticated;
GRANT UPDATE (read) ON TABLE public.direct_messages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.direct_messages TO service_role;
CREATE OR REPLACE FUNCTION public.reminko_delete_dm_thread(p_other_user_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_count INTEGER := 0;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  IF p_other_user_id IS NULL OR p_other_user_id = v_uid THEN
    RAISE EXCEPTION 'invalid_peer';
  END IF;

  UPDATE public.direct_messages
  SET hidden_for = ARRAY(
    SELECT DISTINCT x
    FROM unnest(hidden_for || ARRAY[v_uid]) AS x
  )
  WHERE (
      (sender_id = v_uid AND receiver_id = p_other_user_id)
      OR (sender_id = p_other_user_id AND receiver_id = v_uid)
    )
    AND NOT (v_uid = ANY(hidden_for));

  GET DIAGNOSTICS v_count = ROW_COUNT;

  DELETE FROM public.direct_messages
  WHERE cardinality(hidden_for) >= 2;

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.reminko_delete_dm_thread(UUID)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reminko_delete_dm_thread(UUID)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.reminko_edit_dm_message(p_message_id UUID, p_text TEXT)
RETURNS public.direct_messages
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_row public.direct_messages;
  v_text TEXT := left(trim(COALESCE(p_text, '')), 12000);
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  IF char_length(v_text) < 1 THEN RAISE EXCEPTION 'empty_message'; END IF;

  UPDATE public.direct_messages
  SET message = v_text,
      edited_at = TIMEZONE('utc'::TEXT, NOW())
  WHERE id = p_message_id AND sender_id = v_uid
  RETURNING * INTO v_row;

  IF v_row.id IS NULL THEN RAISE EXCEPTION 'not_found_or_forbidden'; END IF;
  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.reminko_edit_dm_message(UUID, TEXT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reminko_edit_dm_message(UUID, TEXT)
  TO authenticated, service_role;

ALTER TABLE public.dm_group_messages
  DROP CONSTRAINT IF EXISTS dm_group_messages_safe_payload_check;
ALTER TABLE public.dm_group_messages
  ADD CONSTRAINT dm_group_messages_safe_payload_check
  CHECK (char_length(trim(message)) BETWEEN 1 AND 12000);

DROP POLICY IF EXISTS "dm_group_members_select" ON public.dm_group_members;
DROP POLICY IF EXISTS "dm_group_members_insert" ON public.dm_group_members;
DROP POLICY IF EXISTS "dm_group_members_delete" ON public.dm_group_members;
CREATE POLICY "dm_group_members_select" ON public.dm_group_members
  FOR SELECT TO authenticated
  USING (public.reminko_is_dm_group_member(group_id));
CREATE POLICY "dm_group_members_insert_owner_only" ON public.dm_group_members
  FOR INSERT TO authenticated
  WITH CHECK (
    role = 'member'
    AND EXISTS (
      SELECT 1
      FROM public.dm_group_members owner_membership
      WHERE owner_membership.group_id = dm_group_members.group_id
        AND owner_membership.user_id = auth.uid()
        AND owner_membership.role = 'owner'
    )
  );
CREATE POLICY "dm_group_members_delete" ON public.dm_group_members
  FOR DELETE TO authenticated
  USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1
      FROM public.dm_group_members owner_membership
      WHERE owner_membership.group_id = dm_group_members.group_id
        AND owner_membership.user_id = auth.uid()
        AND owner_membership.role = 'owner'
    )
  );

REVOKE ALL ON TABLE public.dm_group_members FROM anon;
REVOKE INSERT, UPDATE ON TABLE public.dm_group_members FROM authenticated;
GRANT SELECT, DELETE ON TABLE public.dm_group_members TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.dm_group_members TO service_role;

CREATE OR REPLACE FUNCTION public.reminko_is_dm_group_owner(p_group_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.dm_group_members m
    WHERE m.group_id = p_group_id
      AND m.user_id = auth.uid()
      AND m.role = 'owner'
  );
$$;

REVOKE ALL ON FUNCTION public.reminko_is_dm_group_owner(UUID)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reminko_is_dm_group_owner(UUID)
  TO authenticated, service_role;

DROP POLICY IF EXISTS "dm_group_members_insert_owner_only" ON public.dm_group_members;
DROP POLICY IF EXISTS "dm_group_members_delete" ON public.dm_group_members;
CREATE POLICY "dm_group_members_insert_owner_only" ON public.dm_group_members
  FOR INSERT TO authenticated
  WITH CHECK (
    role = 'member'
    AND public.reminko_is_dm_group_owner(group_id)
  );
CREATE POLICY "dm_group_members_delete" ON public.dm_group_members
  FOR DELETE TO authenticated
  USING (
    auth.uid() = user_id
    OR public.reminko_is_dm_group_owner(group_id)
  );

DROP POLICY IF EXISTS "dm_group_messages_update" ON public.dm_group_messages;
DROP POLICY IF EXISTS "dm_group_messages_delete" ON public.dm_group_messages;
REVOKE ALL ON TABLE public.dm_group_messages FROM anon;
REVOKE UPDATE, DELETE ON TABLE public.dm_group_messages FROM authenticated;
GRANT SELECT, INSERT ON TABLE public.dm_group_messages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.dm_group_messages TO service_role;

CREATE OR REPLACE FUNCTION public.touch_dm_group_after_message()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE public.dm_groups
  SET updated_at = TIMEZONE('utc'::TEXT, NOW())
  WHERE id = NEW.group_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS touch_dm_group_after_message_trigger ON public.dm_group_messages;
CREATE TRIGGER touch_dm_group_after_message_trigger
AFTER INSERT ON public.dm_group_messages
FOR EACH ROW EXECUTE FUNCTION public.touch_dm_group_after_message();

CREATE OR REPLACE FUNCTION public.reminko_edit_dm_group_message(
  p_message_id UUID,
  p_text TEXT
)
RETURNS public.dm_group_messages
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_row public.dm_group_messages;
  v_text TEXT := left(trim(COALESCE(p_text, '')), 12000);
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  IF char_length(v_text) < 1 THEN RAISE EXCEPTION 'empty_message'; END IF;

  UPDATE public.dm_group_messages
  SET message = v_text,
      edited_at = TIMEZONE('utc'::TEXT, NOW())
  WHERE id = p_message_id AND sender_id = v_uid
  RETURNING * INTO v_row;

  IF v_row.id IS NULL THEN RAISE EXCEPTION 'not_found_or_forbidden'; END IF;
  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.reminko_edit_dm_group_message(UUID, TEXT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reminko_edit_dm_group_message(UUID, TEXT)
  TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 4. Watch Together: server-created rooms, server-calculated VIP, private rows
-- ---------------------------------------------------------------------------

ALTER TABLE public.watch_together_sessions
  DROP CONSTRAINT IF EXISTS watch_together_sessions_safe_values_check;
ALTER TABLE public.watch_together_sessions
  ADD CONSTRAINT watch_together_sessions_safe_values_check
  CHECK (
    session_code ~ '^[A-Z0-9]{8,16}$'
    AND max_participants BETWEEN 2 AND 4
    AND char_length(COALESCE(anime_id, '')) <= 128
    AND char_length(COALESCE(manga_id, '')) <= 128
    AND char_length(COALESCE(video_source, '')) <= 2048
    AND COALESCE(video_source, '') !~ '[<>[:cntrl:]]'
  );

ALTER TABLE public.watch_together_chat
  DROP CONSTRAINT IF EXISTS watch_together_chat_safe_payload_check;
ALTER TABLE public.watch_together_chat
  ADD CONSTRAINT watch_together_chat_safe_payload_check
  CHECK (char_length(trim(message)) BETWEEN 1 AND 2000);

ALTER TABLE public.watch_together_voice_signals
  DROP CONSTRAINT IF EXISTS watch_together_voice_payload_size_check;
ALTER TABLE public.watch_together_voice_signals
  ADD CONSTRAINT watch_together_voice_payload_size_check
  CHECK (octet_length(payload::TEXT) <= 32768);

CREATE OR REPLACE FUNCTION public.wt_has_active_vip(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    public.is_site_creator_user_id(p_user_id)
    OR EXISTS (
      SELECT 1
      FROM public.vip_subscriptions v
      WHERE v.user_id = p_user_id
        AND v.is_active = true
        AND (v.expires_at IS NULL OR v.expires_at > TIMEZONE('utc'::TEXT, NOW()))
    );
$$;

REVOKE ALL ON FUNCTION public.wt_has_active_vip(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.wt_has_active_vip(UUID) TO service_role;

CREATE OR REPLACE FUNCTION public.wt_can_view_session(p_session_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT auth.uid() IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.watch_together_sessions s
      WHERE s.id = p_session_id
        AND (
          s.host_id = auth.uid()
          OR EXISTS (
            SELECT 1
            FROM public.watch_together_participants p
            WHERE p.session_id = s.id AND p.user_id = auth.uid()
          )
          OR EXISTS (
            SELECT 1
            FROM public.friends f
            WHERE f.status = 'accepted'
              AND (
                (f.user_id = auth.uid() AND f.friend_id = s.host_id)
                OR (f.friend_id = auth.uid() AND f.user_id = s.host_id)
              )
          )
        )
    );
$$;

REVOKE ALL ON FUNCTION public.wt_can_view_session(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.wt_can_view_session(UUID) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.wt_create_session(
  p_type TEXT,
  p_anime_id TEXT DEFAULT NULL,
  p_manga_id TEXT DEFAULT NULL
)
RETURNS public.watch_together_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_code TEXT;
  v_row public.watch_together_sessions;
  v_attempt INTEGER;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'auth_required' USING ERRCODE = '42501';
  END IF;
  IF p_type NOT IN ('anime', 'manga') THEN
    RAISE EXCEPTION 'invalid_room_type' USING ERRCODE = '22023';
  END IF;
  IF NOT public.wt_has_active_vip(v_uid) THEN
    RAISE EXCEPTION 'vip_required' USING ERRCODE = '42501';
  END IF;

  IF NOT (
    SELECT r.allowed
    FROM public.security_consume_rate_limit(
      'watch_together.create',
      encode(digest(v_uid::TEXT, 'sha256'), 'hex'),
      10,
      3600
    ) r
  ) THEN
    RAISE LOG 'SECURITY_EVENT|watch_together_create_rate_limited|actor=%', v_uid;
    RAISE EXCEPTION 'room_creation_rate_limited' USING ERRCODE = '54000';
  END IF;

  FOR v_attempt IN 1..8 LOOP
    v_code := upper(substr(replace(gen_random_uuid()::TEXT, '-', ''), 1, 10));
    BEGIN
      INSERT INTO public.watch_together_sessions(
        host_id,
        anime_id,
        manga_id,
        type,
        current_episode,
        current_chapter,
        playback_position,
        is_playing,
        playback_time,
        is_active,
        session_code,
        max_participants,
        last_room_activity_at
      )
      VALUES (
        v_uid,
        CASE WHEN p_type = 'anime' THEN left(NULLIF(trim(p_anime_id), ''), 128) ELSE NULL END,
        CASE WHEN p_type = 'manga' THEN left(NULLIF(trim(p_manga_id), ''), 128) ELSE NULL END,
        p_type,
        CASE WHEN p_type = 'anime' THEN 1 ELSE NULL END,
        CASE WHEN p_type = 'manga' THEN 1 ELSE NULL END,
        0,
        false,
        0,
        true,
        v_code,
        4,
        TIMEZONE('utc'::TEXT, NOW())
      )
      RETURNING * INTO v_row;
      EXIT;
    EXCEPTION WHEN unique_violation THEN
      IF v_attempt = 8 THEN RAISE; END IF;
    END;
  END LOOP;

  INSERT INTO public.watch_together_participants(session_id, user_id, has_vip)
  VALUES (v_row.id, v_uid, public.wt_has_active_vip(v_uid))
  ON CONFLICT (session_id, user_id) DO UPDATE
    SET has_vip = EXCLUDED.has_vip;

  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.wt_create_session(TEXT, TEXT, TEXT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.wt_create_session(TEXT, TEXT, TEXT)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.wt_join_session(
  p_session_id UUID DEFAULT NULL,
  p_session_code TEXT DEFAULT NULL
)
RETURNS public.watch_together_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_code TEXT := upper(trim(COALESCE(p_session_code, '')));
  v_row public.watch_together_sessions;
  v_count INTEGER;
  v_vip_count INTEGER;
  v_non_vip_count INTEGER;
  v_has_vip BOOLEAN;
  v_authorized BOOLEAN := false;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'auth_required' USING ERRCODE = '42501';
  END IF;
  IF p_session_id IS NULL AND v_code = '' THEN
    RAISE EXCEPTION 'room_identifier_required' USING ERRCODE = '22023';
  END IF;

  IF v_code <> '' AND NOT (
    SELECT r.allowed
    FROM public.security_consume_rate_limit(
      'watch_together.join_code',
      encode(digest(v_uid::TEXT, 'sha256'), 'hex'),
      30,
      300
    ) r
  ) THEN
    RAISE LOG 'SECURITY_EVENT|watch_together_join_rate_limited|actor=%', v_uid;
    RAISE EXCEPTION 'room_join_rate_limited' USING ERRCODE = '54000';
  END IF;

  IF v_code <> '' THEN
    SELECT * INTO v_row
    FROM public.watch_together_sessions
    WHERE session_code = v_code
    FOR UPDATE;
    v_authorized := FOUND;
  ELSE
    SELECT * INTO v_row
    FROM public.watch_together_sessions
    WHERE id = p_session_id
    FOR UPDATE;

    IF FOUND THEN
      v_authorized :=
        v_row.host_id = v_uid
        OR EXISTS (
          SELECT 1
          FROM public.watch_together_participants p
          WHERE p.session_id = v_row.id AND p.user_id = v_uid
        )
        OR EXISTS (
          SELECT 1
          FROM public.friends f
          WHERE f.status = 'accepted'
            AND (
              (f.user_id = v_uid AND f.friend_id = v_row.host_id)
              OR (f.friend_id = v_uid AND f.user_id = v_row.host_id)
            )
        )
        OR EXISTS (
          SELECT 1
          FROM public.notifications n
          WHERE n.user_id = v_uid
            AND n.sender_id = v_row.host_id
            AND n.type = 'watch_together_invite'
            AND n.data ->> 'session_id' = v_row.id::TEXT
        );
    END IF;
  END IF;

  IF v_row.id IS NULL OR NOT v_authorized OR NOT COALESCE(v_row.is_active, false) THEN
    RAISE EXCEPTION 'room_not_found_or_forbidden' USING ERRCODE = '42501';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM public.watch_together_participants
  WHERE session_id = v_row.id;

  SELECT
    COUNT(*) FILTER (WHERE has_vip),
    COUNT(*) FILTER (WHERE NOT has_vip)
  INTO v_vip_count, v_non_vip_count
  FROM public.watch_together_participants
  WHERE session_id = v_row.id;

  v_has_vip := public.wt_has_active_vip(v_uid);

  IF NOT EXISTS (
    SELECT 1 FROM public.watch_together_participants
    WHERE session_id = v_row.id AND user_id = v_uid
  ) AND v_count >= LEAST(4, GREATEST(2, COALESCE(v_row.max_participants, 4))) THEN
    RAISE EXCEPTION 'room_full' USING ERRCODE = 'P0001';
  END IF;

  IF NOT v_has_vip
     AND NOT EXISTS (
       SELECT 1 FROM public.watch_together_participants
       WHERE session_id = v_row.id AND user_id = v_uid
     )
     AND (v_vip_count = 0 OR v_non_vip_count >= 1) THEN
    RAISE EXCEPTION 'vip_required_or_guest_slot_full' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.watch_together_participants(session_id, user_id, has_vip)
  VALUES (v_row.id, v_uid, v_has_vip)
  ON CONFLICT (session_id, user_id) DO UPDATE
    SET has_vip = EXCLUDED.has_vip,
        last_ping_at = TIMEZONE('utc'::TEXT, NOW());

  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.wt_join_session(UUID, TEXT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.wt_join_session(UUID, TEXT)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.protect_watch_together_participant()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.has_vip := public.wt_has_active_vip(NEW.user_id);
    NEW.joined_at := TIMEZONE('utc'::TEXT, NOW());
    NEW.player_ready := false;
    NEW.player_ready_at := NULL;
    NEW.last_ping_at := TIMEZONE('utc'::TEXT, NOW());
  ELSE
    NEW.id := OLD.id;
    NEW.session_id := OLD.session_id;
    NEW.user_id := OLD.user_id;
    NEW.has_vip := OLD.has_vip;
    NEW.joined_at := OLD.joined_at;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_watch_together_participant_trigger
  ON public.watch_together_participants;
CREATE TRIGGER protect_watch_together_participant_trigger
BEFORE INSERT OR UPDATE ON public.watch_together_participants
FOR EACH ROW EXECUTE FUNCTION public.protect_watch_together_participant();

DROP POLICY IF EXISTS "wt_sessions_select" ON public.watch_together_sessions;
DROP POLICY IF EXISTS "wt_sessions_insert" ON public.watch_together_sessions;
DROP POLICY IF EXISTS "wt_sessions_update" ON public.watch_together_sessions;
CREATE POLICY "wt_sessions_select" ON public.watch_together_sessions
  FOR SELECT TO authenticated
  USING (public.wt_can_view_session(id));
CREATE POLICY "wt_sessions_update" ON public.watch_together_sessions
  FOR UPDATE TO authenticated
  USING (host_id = auth.uid())
  WITH CHECK (host_id = auth.uid());

DROP POLICY IF EXISTS "wt_participants_select" ON public.watch_together_participants;
DROP POLICY IF EXISTS "wt_participants_insert" ON public.watch_together_participants;
DROP POLICY IF EXISTS "wt_participants_update_own" ON public.watch_together_participants;
CREATE POLICY "wt_participants_select" ON public.watch_together_participants
  FOR SELECT TO authenticated
  USING (public.wt_can_view_session(session_id));
CREATE POLICY "wt_participants_update_own" ON public.watch_together_participants
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

REVOKE ALL ON TABLE public.watch_together_sessions FROM anon;
REVOKE INSERT, DELETE, UPDATE ON TABLE public.watch_together_sessions FROM authenticated;
GRANT SELECT ON TABLE public.watch_together_sessions TO authenticated;
GRANT UPDATE (
  anime_id, manga_id, current_episode, current_chapter, playback_position,
  is_playing, playback_time, video_source, is_active, updated_at,
  sync_hold, sync_hold_reason, sync_generation, host_screen_broadcast,
  last_room_activity_at
) ON TABLE public.watch_together_sessions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.watch_together_sessions TO service_role;

REVOKE ALL ON TABLE public.watch_together_participants FROM anon;
REVOKE INSERT, UPDATE ON TABLE public.watch_together_participants FROM authenticated;
GRANT SELECT, DELETE ON TABLE public.watch_together_participants TO authenticated;
GRANT UPDATE (player_ready, player_ready_at, last_ping_at)
  ON TABLE public.watch_together_participants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.watch_together_participants TO service_role;

REVOKE ALL ON TABLE public.watch_together_chat, public.watch_together_voice_signals FROM anon;
GRANT SELECT, INSERT ON TABLE public.watch_together_chat, public.watch_together_voice_signals
  TO authenticated;

CREATE OR REPLACE FUNCTION public.wt_close_idle_session_if_needed(p_session_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_row public.watch_together_sessions%ROWTYPE;
  v_last TIMESTAMPTZ;
  v_chat_last TIMESTAMPTZ;
  v_is_service BOOLEAN :=
    current_user IN ('postgres', 'service_role')
    OR lower(COALESCE(auth.jwt() ->> 'role', '')) = 'service_role';
BEGIN
  SELECT * INTO v_row
  FROM public.watch_together_sessions
  WHERE id = p_session_id;

  IF NOT FOUND OR NOT COALESCE(v_row.is_active, false) THEN
    RETURN false;
  END IF;

  IF NOT v_is_service
     AND auth.uid() <> v_row.host_id
     AND NOT EXISTS (
       SELECT 1 FROM public.watch_together_participants p
       WHERE p.session_id = p_session_id AND p.user_id = auth.uid()
     ) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF COALESCE(v_row.is_playing, false) THEN RETURN false; END IF;

  SELECT MAX(c.created_at) INTO v_chat_last
  FROM public.watch_together_chat c
  WHERE c.session_id = p_session_id;

  v_last := GREATEST(
    v_row.created_at,
    COALESCE(v_row.last_room_activity_at, v_row.created_at),
    COALESCE(v_chat_last, v_row.created_at)
  );

  IF v_last >= TIMEZONE('utc'::TEXT, NOW()) - INTERVAL '30 minutes' THEN
    RETURN false;
  END IF;

  UPDATE public.watch_together_sessions
  SET is_active = false,
      updated_at = TIMEZONE('utc'::TEXT, NOW())
  WHERE id = p_session_id AND is_active = true;
  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION public.wt_close_idle_session_if_needed(UUID)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.wt_close_idle_session_if_needed(UUID)
  TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.wt_close_idle_sessions()
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.wt_close_idle_sessions()
  TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 5. Server-only analytics ingestion
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_site_visit_visitor_created
  ON public.site_visit_events(visitor_id, created_at DESC);

ALTER TABLE public.site_visit_events
  DROP CONSTRAINT IF EXISTS site_visit_events_safe_payload_check;
ALTER TABLE public.site_visit_events
  ADD CONSTRAINT site_visit_events_safe_payload_check
  CHECK (
    char_length(visitor_id) BETWEEN 8 AND 64
    AND char_length(path) BETWEEN 1 AND 1024
    AND char_length(COALESCE(page_title, '')) <= 300
    AND char_length(COALESCE(referrer, '')) <= 1024
    AND char_length(COALESCE(user_agent, '')) <= 512
    AND event_kind IN ('pageview', 'action')
    AND char_length(COALESCE(event_label, '')) <= 200
    AND octet_length(COALESCE(meta, '{}'::JSONB)::TEXT) <= 4096
    AND created_at <= TIMEZONE('utc'::TEXT, NOW()) + INTERVAL '1 minute'
  );

CREATE OR REPLACE FUNCTION public.normalize_site_visit_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.created_at := TIMEZONE('utc'::TEXT, NOW());
  NEW.visitor_id := left(trim(NEW.visitor_id), 64);
  NEW.path := left(split_part(trim(NEW.path), '?', 1), 1024);
  NEW.page_title := NULLIF(left(trim(COALESCE(NEW.page_title, '')), 300), '');
  NEW.referrer := NULLIF(left(trim(COALESCE(NEW.referrer, '')), 1024), '');
  NEW.user_agent := NULLIF(left(trim(COALESCE(NEW.user_agent, '')), 512), '');
  NEW.event_kind := CASE WHEN NEW.event_kind = 'action' THEN 'action' ELSE 'pageview' END;
  NEW.event_label := NULLIF(left(trim(COALESCE(NEW.event_label, '')), 200), '');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS normalize_site_visit_event_trigger ON public.site_visit_events;
CREATE TRIGGER normalize_site_visit_event_trigger
BEFORE INSERT ON public.site_visit_events
FOR EACH ROW EXECUTE FUNCTION public.normalize_site_visit_event();

DROP POLICY IF EXISTS "site_visit_events_insert" ON public.site_visit_events;
REVOKE INSERT, UPDATE ON TABLE public.site_visit_events FROM anon, authenticated;
REVOKE SELECT, DELETE ON TABLE public.site_visit_events FROM anon;
GRANT SELECT, DELETE ON TABLE public.site_visit_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.site_visit_events TO service_role;

DELETE FROM public.site_visit_events
WHERE created_at < TIMEZONE('utc'::TEXT, NOW()) - INTERVAL '90 days';

-- ---------------------------------------------------------------------------
-- 6. Friend transitions, chat mutation controls, notification anti-spam
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.protect_friend_request_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_allowed BOOLEAN;
BEGIN
  IF auth.role() = 'authenticated' THEN
    IF TG_OP = 'INSERT' THEN
      NEW.user_id := auth.uid();
      IF NEW.friend_id IS NULL OR NEW.friend_id = auth.uid() THEN
        RAISE EXCEPTION 'invalid_friend' USING ERRCODE = '22023';
      END IF;
      SELECT r.allowed INTO v_allowed
      FROM public.security_consume_rate_limit(
        'friend.request',
        encode(digest(auth.uid()::TEXT, 'sha256'), 'hex'),
        30,
        3600
      ) r;
      IF NOT COALESCE(v_allowed, false) THEN
        RAISE LOG 'SECURITY_EVENT|friend_request_rate_limited|actor=%', auth.uid();
        RAISE EXCEPTION 'friend_request_rate_limited' USING ERRCODE = '54000';
      END IF;
      NEW.status := 'pending';
      NEW.accepted_at := NULL;
      NEW.created_at := TIMEZONE('utc'::TEXT, NOW());
    ELSE
      IF OLD.user_id IS DISTINCT FROM NEW.user_id
         OR OLD.friend_id IS DISTINCT FROM NEW.friend_id
         OR OLD.created_at IS DISTINCT FROM NEW.created_at
         OR auth.uid() <> OLD.friend_id
         OR OLD.status <> 'pending'
         OR NEW.status NOT IN ('accepted', 'blocked') THEN
        RAISE LOG 'SECURITY_EVENT|friend_transition_blocked|actor=%|friendship=%',
          COALESCE(auth.uid()::TEXT, 'anonymous'), COALESCE(OLD.id::TEXT, '');
        RAISE EXCEPTION 'invalid_friend_transition' USING ERRCODE = '42501';
      END IF;
      NEW.accepted_at := CASE
        WHEN NEW.status = 'accepted' THEN TIMEZONE('utc'::TEXT, NOW())
        ELSE NULL
      END;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_friend_request_transition_trigger ON public.friends;
CREATE TRIGGER protect_friend_request_transition_trigger
BEFORE INSERT OR UPDATE ON public.friends
FOR EACH ROW EXECUTE FUNCTION public.protect_friend_request_transition();

DROP POLICY IF EXISTS "friends_insert" ON public.friends;
DROP POLICY IF EXISTS "friends_update" ON public.friends;
CREATE POLICY "friends_insert" ON public.friends
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND user_id <> friend_id
    AND status = 'pending'
  );
CREATE POLICY "friends_update_recipient" ON public.friends
  FOR UPDATE TO authenticated
  USING (auth.uid() = friend_id AND status = 'pending')
  WITH CHECK (auth.uid() = friend_id);

REVOKE ALL ON TABLE public.friends FROM anon;
REVOKE UPDATE ON TABLE public.friends FROM authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.friends TO authenticated;
GRANT UPDATE (status, accepted_at) ON TABLE public.friends TO authenticated;

ALTER TABLE public.global_chat_messages
  DROP CONSTRAINT IF EXISTS global_chat_messages_safe_payload_check;
ALTER TABLE public.global_chat_messages
  ADD CONSTRAINT global_chat_messages_safe_payload_check
  CHECK (char_length(trim(message)) BETWEEN 1 AND 300);

DROP TRIGGER IF EXISTS tr_global_chat_automod_before_insert
  ON public.global_chat_messages;
DROP TRIGGER IF EXISTS tr_global_chat_automod_before_write
  ON public.global_chat_messages;
CREATE TRIGGER tr_global_chat_automod_before_write
BEFORE INSERT OR UPDATE OF message ON public.global_chat_messages
FOR EACH ROW EXECUTE FUNCTION public.trg_global_chat_automod_before_insert();

DROP POLICY IF EXISTS "chat_update_own" ON public.global_chat_messages;
DROP POLICY IF EXISTS "chat_delete" ON public.global_chat_messages;
DROP POLICY IF EXISTS "chat_update_creator" ON public.global_chat_messages;
CREATE POLICY "chat_soft_delete_own" ON public.global_chat_messages
  FOR UPDATE TO authenticated
  USING (
    auth.uid() = user_id
    OR public.is_site_creator_user_id(auth.uid())
  )
  WITH CHECK (
    auth.uid() = user_id
    OR public.is_site_creator_user_id(auth.uid())
  );
REVOKE INSERT, UPDATE, DELETE ON TABLE public.global_chat_messages FROM anon;
REVOKE UPDATE, DELETE ON TABLE public.global_chat_messages FROM authenticated;
GRANT SELECT ON TABLE public.global_chat_messages TO anon, authenticated;
GRANT INSERT ON TABLE public.global_chat_messages TO authenticated;
GRANT UPDATE (deleted_at) ON TABLE public.global_chat_messages TO authenticated;

CREATE OR REPLACE FUNCTION public.normalize_global_chat_soft_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF current_user = 'authenticated' THEN
    IF OLD.deleted_at IS NOT NULL THEN
      RAISE EXCEPTION 'message_already_deleted' USING ERRCODE = '42501';
    END IF;
    NEW.deleted_at := TIMEZONE('utc'::TEXT, NOW());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS normalize_global_chat_soft_delete_trigger
  ON public.global_chat_messages;
CREATE TRIGGER normalize_global_chat_soft_delete_trigger
BEFORE UPDATE OF deleted_at ON public.global_chat_messages
FOR EACH ROW EXECUTE FUNCTION public.normalize_global_chat_soft_delete();

CREATE OR REPLACE FUNCTION public.protect_notification_write()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_allowed BOOLEAN;
BEGIN
  IF auth.role() = 'authenticated' THEN
    NEW.sender_id := auth.uid();
    NEW.created_at := TIMEZONE('utc'::TEXT, NOW());
    NEW.read := false;
    NEW.read_at := NULL;

    IF NOT public.is_site_creator_user_id(auth.uid()) THEN
      SELECT r.allowed INTO v_allowed
      FROM public.security_consume_rate_limit(
        'notification.send',
        encode(digest(auth.uid()::TEXT, 'sha256'), 'hex'),
        20,
        60
      ) r;
      IF NOT COALESCE(v_allowed, false) THEN
        RAISE LOG 'SECURITY_EVENT|notification_rate_limited|actor=%', auth.uid();
        RAISE EXCEPTION 'notification_rate_limited' USING ERRCODE = '54000';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_notification_write_trigger ON public.notifications;
CREATE TRIGGER protect_notification_write_trigger
BEFORE INSERT ON public.notifications
FOR EACH ROW EXECUTE FUNCTION public.protect_notification_write();

DROP POLICY IF EXISTS "notifications_insert_creator" ON public.notifications;
CREATE POLICY "notifications_insert_creator" ON public.notifications
  FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = auth.uid()
    AND public.is_site_creator_user_id(auth.uid())
  );

-- ---------------------------------------------------------------------------
-- 7. Server-owned state, giveaway integrity, storage identity
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "minko_ai_state_all" ON public.minko_ai_state;
CREATE POLICY "minko_ai_state_select_own" ON public.minko_ai_state
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);
REVOKE ALL ON TABLE public.minko_ai_state FROM anon;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.minko_ai_state FROM authenticated;
GRANT SELECT ON TABLE public.minko_ai_state TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.minko_ai_state TO service_role;

CREATE OR REPLACE FUNCTION public.is_verified_nonanonymous_user(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM auth.users u
    WHERE u.id = p_user_id
      AND u.email IS NOT NULL
      AND u.email_confirmed_at IS NOT NULL
      AND COALESCE((u.raw_app_meta_data ->> 'provider') = 'anonymous', false) = false
  );
$$;

REVOKE ALL ON FUNCTION public.is_verified_nonanonymous_user(UUID)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_verified_nonanonymous_user(UUID)
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.enforce_verified_giveaway_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_row JSONB := to_jsonb(NEW);
  v_uid UUID := COALESCE(
    auth.uid(),
    NULLIF(v_row ->> 'user_id', '')::UUID,
    NULLIF(v_row ->> 'registered_user_id', '')::UUID
  );
BEGIN
  IF v_uid IS NOT NULL
     AND NOT public.is_verified_nonanonymous_user(v_uid) THEN
    RAISE LOG 'SECURITY_EVENT|giveaway_unverified_identity_blocked|actor=%|table=%',
      COALESCE(auth.uid()::TEXT, 'anonymous'), TG_TABLE_NAME;
    RAISE EXCEPTION 'verified_account_required' USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  v_table TEXT;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'giveaway_participants',
    'giveaway_preregistrations',
    'giveaway_ref_registrations'
  ]
  LOOP
    IF to_regclass('public.' || v_table) IS NOT NULL THEN
      EXECUTE format('DROP TRIGGER IF EXISTS enforce_verified_giveaway_identity_trigger ON public.%I', v_table);
      EXECUTE format(
        'CREATE TRIGGER enforce_verified_giveaway_identity_trigger BEFORE INSERT OR UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.enforce_verified_giveaway_identity()',
        v_table
      );
    END IF;
  END LOOP;
END
$$;

REVOKE ALL ON FUNCTION public.giveaway_record_click(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.giveaway_record_click(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) TO service_role;

DROP POLICY IF EXISTS "anime_4k_videos_creator_write" ON storage.objects;
CREATE POLICY "anime_4k_videos_creator_write"
ON storage.objects
FOR ALL
TO authenticated
USING (
  bucket_id = 'anime-4k-videos'
  AND public.is_site_creator_user_id(auth.uid())
)
WITH CHECK (
  bucket_id = 'anime-4k-videos'
  AND public.is_site_creator_user_id(auth.uid())
);

-- ---------------------------------------------------------------------------
-- 8. Atomic avatar generation quota
-- ---------------------------------------------------------------------------

ALTER TABLE public.avatar_ai_generations
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'completed';
ALTER TABLE public.avatar_ai_generations
  DROP CONSTRAINT IF EXISTS avatar_ai_generations_status_check;
ALTER TABLE public.avatar_ai_generations
  ADD CONSTRAINT avatar_ai_generations_status_check
  CHECK (status IN ('reserved', 'completed', 'failed'));

CREATE INDEX IF NOT EXISTS idx_avatar_ai_generations_quota
  ON public.avatar_ai_generations(user_id, status, created_at DESC);

CREATE OR REPLACE FUNCTION public.reserve_avatar_ai_generation(
  p_user_id UUID,
  p_limit INTEGER DEFAULT 3,
  p_window_hours INTEGER DEFAULT 24
)
RETURNS TABLE(
  allowed BOOLEAN,
  reservation_id UUID,
  used INTEGER,
  remaining INTEGER,
  resets_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_now TIMESTAMPTZ := TIMEZONE('utc'::TEXT, NOW());
  v_limit INTEGER := LEAST(20, GREATEST(1, COALESCE(p_limit, 3)));
  v_hours INTEGER := LEAST(168, GREATEST(1, COALESCE(p_window_hours, 24)));
  v_used INTEGER;
  v_id UUID;
  v_oldest TIMESTAMPTZ;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'user_required' USING ERRCODE = '22023';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id::TEXT, 0));

  SELECT COUNT(*)::INTEGER, MIN(created_at)
  INTO v_used, v_oldest
  FROM public.avatar_ai_generations
  WHERE user_id = p_user_id
    AND created_at >= v_now - make_interval(hours => v_hours)
    AND (
      status = 'completed'
      OR (status = 'reserved' AND created_at >= v_now - INTERVAL '10 minutes')
    );

  IF v_used >= v_limit THEN
    RETURN QUERY SELECT
      false,
      NULL::UUID,
      v_used,
      0,
      COALESCE(v_oldest + make_interval(hours => v_hours), v_now + make_interval(hours => v_hours));
    RETURN;
  END IF;

  INSERT INTO public.avatar_ai_generations(user_id, status, created_at)
  VALUES (p_user_id, 'reserved', v_now)
  RETURNING id INTO v_id;

  RETURN QUERY SELECT
    true,
    v_id,
    v_used + 1,
    GREATEST(0, v_limit - v_used - 1),
    NULL::TIMESTAMPTZ;
END;
$$;

CREATE OR REPLACE FUNCTION public.finish_avatar_ai_generation(
  p_reservation_id UUID,
  p_success BOOLEAN
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE public.avatar_ai_generations
  SET status = CASE WHEN COALESCE(p_success, false) THEN 'completed' ELSE 'failed' END
  WHERE id = p_reservation_id
    AND status = 'reserved';
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.avatar_ai_generation_quota(
  p_user_id UUID,
  p_limit INTEGER DEFAULT 3,
  p_window_hours INTEGER DEFAULT 24
)
RETURNS TABLE(used INTEGER, remaining INTEGER, resets_at TIMESTAMPTZ)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH params AS (
    SELECT
      LEAST(20, GREATEST(1, COALESCE(p_limit, 3))) AS lim,
      LEAST(168, GREATEST(1, COALESCE(p_window_hours, 24))) AS hours,
      TIMEZONE('utc'::TEXT, NOW()) AS now_at
  ),
  usage AS (
    SELECT COUNT(*)::INTEGER AS cnt, MIN(g.created_at) AS oldest
    FROM public.avatar_ai_generations g, params p
    WHERE g.user_id = p_user_id
      AND g.created_at >= p.now_at - make_interval(hours => p.hours)
      AND (
        g.status = 'completed'
        OR (g.status = 'reserved' AND g.created_at >= p.now_at - INTERVAL '10 minutes')
      )
  )
  SELECT
    u.cnt,
    GREATEST(0, p.lim - u.cnt),
    CASE WHEN u.cnt >= p.lim THEN u.oldest + make_interval(hours => p.hours) ELSE NULL END
  FROM usage u CROSS JOIN params p;
$$;

REVOKE ALL ON FUNCTION public.reserve_avatar_ai_generation(UUID, INTEGER, INTEGER)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.finish_avatar_ai_generation(UUID, BOOLEAN)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.avatar_ai_generation_quota(UUID, INTEGER, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_avatar_ai_generation(UUID, INTEGER, INTEGER)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.finish_avatar_ai_generation(UUID, BOOLEAN)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.avatar_ai_generation_quota(UUID, INTEGER, INTEGER)
  TO service_role;

-- Keep only the intended browser/service grants after legacy defaults.
REVOKE TRUNCATE, REFERENCES, TRIGGER
ON ALL TABLES IN SCHEMA public
FROM anon, authenticated;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;

